version: 1

before:
  hooks:
    - go mod tidy

builds:
  - id: bootly
    main: ./cmd
    binary: bootly
    env:
      - CGO_ENABLED=0
    flags:
      - -v
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}}
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc